### ISSUE TITLE
Unable to load guidelines - Incorrect File Format Error

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#13]
I am facing an issue while trying to load the 'guidelines.md' file in my project within the application. Although the file is in Markdown format, the application displays an error message stating that the file format is incorrect. Consequently, I am unable to load the file

**Comment by confusedSerge** [comment]
Would it be possible for you to post a small file/selection to recreate the problem?

**Comment by FrancescoPeriti** [comment]
[guidelines.md](https://github.com/Garrafao/phitag/files/12066806/guidelines.md)

**Comment by confusedSerge** [comment]
I am unable to recreate the problem. When I upload the file in my private project it is displayed correctly. Are you uploading the file with the `.md` ending?

**Comment by FrancescoPeriti** [comment]
Yes, I'm doing it. 
[my project] -> [overview] -> [guidelines:] -> button + 

Then, I select my file: guidelines.md. The error is: please select a markdown file

**Comment by confusedSerge** [comment]
A few more questions:
- Have you tried it with the file you posted above? 
- Is you file encoded in UTF-8?
- What Browser are you using?
- What OS are you using?

**Comment by FrancescoPeriti** [comment]
[guidelines.md](https://github.com/Garrafao/phitag/files/12069397/guidelines.md)

- Yes, I tried with it.
- I think the file I sent was utf-8. Anyway, I've converted it back to utf-8 and am attaching it in this answer
- I tried chrome and firefox
- I'm using Windows 10.

**Comment by confusedSerge** [comment]
I found the problem. Fix will be online soon (about tomorrow)
