### ISSUE TITLE
How to delete data and project?

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#15]
I need assistance on how to properly delete data and projects. I don't see any options available in PhiTag to do this

**Comment by confusedSerge** [comment]
Currently, we do not allow to delete projects or data besides judgements. Tomorrow we will update the online version to support deletion of projects, which can be done from the project overview tab by the owner of the project.

**Comment by FrancescoPeriti** [comment]
Ok, thanks for your assistance

**Comment by confusedSerge** [comment]
The update is online @FrancescoPeriti
