### ISSUE TITLE
Page not found - Continue reading

### ISSUE THREAD

**Issue by AinaIanemahy** [Garrafao/phitag#16]
![image](https://github.com/Garrafao/phitag/assets/57177003/b394fa85-6b1e-44ed-9e9a-b0293b656ab5)
Clicking on continue reading redirects to the main menu and gives a page not found error.

**Comment by AinaIanemahy** [comment]
- on the https://phitag.ims.uni-stuttgart.de/faq page the link to about https://phitag.ims.uni-stuttgart.de/about

**Comment by confusedSerge** [comment]
Will be updated. Thanks!
