### ISSUE TITLE
Checking of tutorial annotation

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/phitag#17]
currently, an annotator needs to completely match tutorial annotations to be able to pass it. This should be relaxed to a certain threshold with Fleiss' Kappa.

**Comment by FrancescoPeriti** [comment]
I just completed the tutorial of my project, but when I click on the "send" button this error arises: _error while evaluating tutorial: Tutorial not completed. The judgments are wrong!_ As a result, the tutorial is not marked as completed and the annotations I made are not saved. 

Is this problem related?

**Comment by confusedSerge** [comment]
We are currently extending the tutorial phases to include more meaningful statistics for evaluation and storing resulting statistics to be viewed in the statistics tab. In general we do not store tutorial judgements, as if a tutorial needs to be retaken, previous annotations could/would interfere with the statistic calculations.

Is storing the  judgements of tutorials something that would be of interest?

**Comment by Garrafao** [comment]
I think storing the judgments is interesting for many researchers.

**Comment by Garrafao** [comment]
After finishing the tutorial, this shown as "incompleted", probably because I didn't pass. Better would be a label "not passed" then.

**Comment by Garrafao** [comment]
Also, the message when finishing the tutorial says that statistics are shown on the "project" overview, however it should say "phase" overview.

**Comment by confusedSerge** [comment]
I will open a new Feature Improvement Issue for storing the judgements of a tutorial and close this one, as the agreement statistic was extended.
