### ISSUE TITLE
Allow the annotation phase only after completing the tutorial phase

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#19]
Currently, it seems that annotators can annotate even without completing the tutorial. Isn't tutorial completion mandatory before accessing the true annotation?

I'm facing this issue in a use pair annotation project

**Comment by confusedSerge** [comment]
Hey, thanks for reaching out. This is currently not as intuitive as it should be and I will soon provide a guide. We have now extended the possibility to choose which statistic should be used for validating a successful tutorial completion and hence tutorials before the 26/07/2023 are invalid and cannot be used anymore. 

Moreover, as we wanted to allow for tutorials to not be mandatory, a tutorial after creation just is. You have to add this tutorial as a requirement to be mandatory to be completed before the phase can be annotated. Furthermore, if you wish to change out tutorials, you can remove and add different tutorials over this interface. 

Hopefully this helps for now and I'll let you know when the guide is online.

**Comment by confusedSerge** [comment]
This evening a new version will be online with an updated guide to [How To Annotation Manager](https://phitag.ims.uni-stuttgart.de/guide/how-to-annotation-manager) which also gives a small visual introduction.
