### ISSUE TITLE
Updating user data without updating username

### ISSUE THREAD

**Issue by AinaIanemahy** [Garrafao/phitag#20]
Trying to update the user data without changing the username gives a 'cannot change username to the same value' error message. This should be possible.

**Comment by AinaIanemahy** [comment]
Also, after updating, the data does not seem to have changed (even though there is an update successful message). I changed my username but still the old name is the correct one and the change in use case was not retained.

**Comment by sachinn12** [comment]
All parameters except the username are now updating. Since the username is the primary key and is connected to other tables, it cannot be updated. Commit: https://github.com/Garrafao/phitag/commit/b0139bc25951bdb42c295ee64c4f796839f064d4
