### ISSUE TITLE
Link to example projects

### ISSUE THREAD

**Issue by AinaIanemahy** [Garrafao/phitag#21]
The github repo with the example projects should be linked more prominently (on the startpage before login and maybe in the faq).

**Comment by confusedSerge** [comment]
I am uncertain which example projects you are referring to. The projects for phitag itself, or the https://github.com/ChangeIsKey/annotation_standardization repository

**Comment by AinaIanemahy** [comment]
I do not remember the context for this, so I propose to close this issue. It might be that I was referring to the Phitag example project on the website but I don't know why I should have written github repo in that case.
