### ISSUE TITLE
Uploading Instances/"Phase not ready for annotation" error

### ISSUE THREAD

**Issue by nwhal** [Garrafao/phitag#23]
It is not immediately clear how instances are meant to be uploaded. The phase not ready error should specify what items need to be added to begin the annotation phase and how to upload them.

**Comment by confusedSerge** [comment]
Hey, thanks for commenting. Currently, the error/info should say something along the lines: "no instances found". I.e. you have to upload some instances for your phase, which you can do by clicking on the phase itself.

Check out the following [guide]( https://phitag.ims.uni-stuttgart.de/guide/how-to-annotation-manager) which might help you with the first steps.
