### ISSUE TITLE
Statistics displaying deleted annotations

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#24]
My project's statistics section continues to consider my deleted annotations. Despite removing some annotations, the total number of annotations is still displayed in the statistics area. It seems that the deleted annotations are present in the system, although they are not visible in the judgments area of the annotation phase.

Additionally, I am unable to reannotate the pairs for which I previously deleted my annotations. When attempting to restart the annotation, the system automatically directs me to the next pair after the last one I annotated, which prevents me from reassessing specific pairs for which I changed my mind or accidentally pressed the wrong button

**Comment by confusedSerge** [comment]
The system does not consider the current annotations in the system, but rather annotations in general, meaning removing an annotation/judgement does not actually affect the number of judgements done on the platform, hence the number does not decrease. 

Towards the second point. As we work with a stateless model, the annotation process does only move forward and you are only able to change your annotation on the phase tab "judgement" or "history". 

I hope this clarifies some misconception.
