### ISSUE TITLE
Access denied to resource

### ISSUE THREAD

**Issue by nwhal** [Garrafao/phitag#28]
"access denied to resource" when clicking annotate on phase.  Needs detailed instructions on how to get started with annotation. *Also a typo where it says "access denided"

**Comment by nwhal** [comment]
This problem only comes up when the phase is marked as a tutorial. Normal annotation in is possible.

**Comment by Garrafao** [comment]
@confusedSerge : if you mark the phase as "is tutorial", does this mean that the phase is the tutorial or that you need to pass a tutorial in order to annotate? If there is a confusion here, we should make it clear in the new tutorial guide.

**Comment by confusedSerge** [comment]
The [How To Annotation Manager](https://phitag.ims.uni-stuttgart.de/guide/how-to-annotation-manager) now has a sub-section dedicated to tutorials. In short, the button is a toggle to either show normal phases or tutorials. 

The access denied information gives some hint on what is missing, which in this case might be the instances to be annotated. 

If there is something unclear, please reopen this issue and if there is a message by the system, please included it in full.
