### ISSUE TITLE
How can I change the annotation agreement strategy?

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#32]
I have just set an annotation agreement strategy for my phase, but I can't change it. If there is a way to do it, I don't find it

**Comment by confusedSerge** [comment]
We do not allow changing the strategy, as this would affect users which already passed the tutorial and it is not clear if these users then need to be reevaluated or not.

**Comment by sachinn12** [comment]
Not required to implement this,  so closing this issues.
