### ISSUE TITLE
I can't delete my [tutorial] phases

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#33]
I have just loaded my tutorial data, but I have changed my mind and I want to change the phase with different data. How can I remove or replace the tutorial phase from my project?

**Comment by FrancescoPeriti** [comment]
Actually, I can delete a full project, but not a specific annotation phase

**Comment by sachinn12** [comment]
Both tutorial and not tutorial phase can be deleted without deleting a project. commit : https://github.com/Garrafao/phitag/commit/b0139bc25951bdb42c295ee64c4f796839f064d4
