### ISSUE TITLE
Tutorial annotations are not saved [bug]

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#48]
Annotations made during the tutorial phase are not saved in the system. This does not allow to conduct post-processing or assess annotator agreement, making it difficult to evaluate the quality and consistency of annotations.

**Comment by sachinn12** [comment]
All the annotations made by the annotator in the tutorial phase are now being saved and can be viewed in a tutorial history page. (commit : captcha-milestone-v1)
