### ISSUE TITLE
Ranking Task

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/phitag#55]
Integration of a text instance ranking task. Annotators are presented a number of text instances like this:

text 1
text 2
text 3
text 4

Their job is to rank these according to some property such as described in the guidelines. This could be done by assigning numbers for ranks or drag-and-drop (probably better).

Additionally, we need a variation of this task where annotators order the texts as compared to some target text like this:

target_text 

text 1
text 2
text 3
text 4

target_text could also be preceded by some question like

Which text below is most related to target_text?
target_text 

text 1
text 2
text 3
text 4

**Comment by Garrafao** [comment]
Details to be discussed here. Can we imagine more ranking conditions?

**Comment by Garrafao** [comment]
Another condition is to compare two pairs simultaneously:

text1
text2

text3
text4

And to ask annotators to which of these a property applies more, e.g. which of the pairs is more semantically related?

This task condition is used in [this paper](https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.13029).

**Comment by sachinn12** [comment]
All there different types of ranking task  including guideline has been implemented. (commit: captcha-milestone-v1)
