### ISSUE TITLE
Data distribution over annotators

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/phitag#57]
This issue aims to collect possible types of data distribution over annotators. Currently, we allow for 
- full allocation of annotation instances per phase to all annotators
- Randomly sampling annotation instances per annotator

To be discussed, which possibilities should be added.

**Comment by sachinn12** [comment]
Another option would be: 

- Assigning n-sized slices to annotators
- Assigning in a way to guarantee that each instances has at least x annotators.

**Comment by Garrafao** [comment]
n-sized random sample per annotator

**Comment by sachinn12** [comment]
This feature has been implemented, including the information that can be seen in the sampling strategy section while creating a phase. (Commit: captcha-milestone-v1)
