### ISSUE TITLE
 notification to annotators that tutorial is not taken

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/phitag#66]
When annotators try to annotate a non-tutorial phase for which a tutorial is defined as precondition, they don't get a specific message why they cannot annotate that phase if they didn't pass the tutorial yet. This should be a specific message that they cannot annotate because they didn't take the tutorial yet.

**Comment by sachinn12** [comment]
user now specific message when they try to annotate phase without passing tutorial phase. commit: https://github.com/Garrafao/phitag/commit/d19443ec46796e1fa099445f31aab8c8a9e45463
