### ISSUE TITLE
pair annotation label clarification 

### ISSUE THREAD

**Issue by cowsock** [Garrafao/phitag#78]
Hi all,

It would be useful for a semantic similarity task to have a reminder about the polarity of the numeric annotation scale to be displayed on the page. 

When creating Instances for my task, I tried seeing if it would look ok to just include the explanation as part of the label set / non label text fields, but the result was along the lines of this screenshot:

![Screenshot from 2023-12-22 11-26-44](https://github.com/Garrafao/phitag/assets/4561660/f08143b7-3955-4037-a89c-1263e1bd4340)

Would it be possible for the Instances file format to include an extra free-text field that could be displayed below the bank of annotation buttons?

**Comment by Garrafao** [comment]
> Would it be possible for the Instances file format to include an extra free-text field that could be displayed below the bank of annotation buttons?

That would be possible, but it would inflate the upload format. Would another possible solution be to improve the label display? This could e.g. be done by making the button box wider/flexible.

**Comment by cowsock** [comment]
That would also be fine!

**Comment by sachinn12** [comment]
I will make this label box responsive to the text, the box size will be automatically adjusted depends upon the text length. changes will be visible on next deployment( before 22 Jan)

**Comment by sachinn12** [comment]
The label boxes are now responsive to the size of text. (Commit: captcha-milestone-v1)
