### ISSUE TITLE
Phitag Setup Issue

### ISSUE THREAD

**Issue by nilsreiter** [Garrafao/phitag#90]
Hey,

we (me + @pagelj) are working on integrating Phitag into our docker-based environment. A few minor things had to be adapted (see [our fork here](https://github.com/companno/phitag)), but we ran into one issue that we are not able to solve:

> phitag_1           | 2024-02-22 08:29:44.419  WARN 239 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: class path resource [db/changelog/computational-annotator-seeds/] cannot be resolved to URL because it does not exist

We will probably not use any computational annotators -- is there a way to disable/remove this part or fix the issue? The backend seems to shutdown after this.

Thanks

**Comment by Garrafao** [comment]
@sachinn12 Any suggestions?
@nilsreiter Could you maybe create a pull request with the changes you made in you fork?

**Comment by sachinn12** [comment]
@nilsreiter  Please delete the database ,then restart the application.

use command: podman/docker  rm <image_name>  -f

to find the image name: podman/docker ps

**Comment by nilsreiter** [comment]
Thanks, I'll try that. 

@Garrafao: So far, the only changes are the hostname of the database and the base path for the UI, so that it runs in a subdirectory. You may want to consider exposing those as configuration options though.

**Comment by sachinn12** [comment]
@nilsreiter  Could you please provide me more details  on why you want to change the hostname of the db and the base path for the UI?

**Comment by nilsreiter** [comment]
@sachinn12 DB: Because Phitag runs in a docker compose environment, and the db runs in a different container than Phitag. Base path: Same thing, it should be reachable under `DOMAIN/phitag` (next to `DOMAIN/inception` etc.).

**Comment by Garrafao** [comment]
Thanks. We could mention these 2 points in the readme, or do you have another proposal?

**Comment by nilsreiter** [comment]
Deleting the database didn't help. I don't know anything about Liquibase, but it seems that the config files below `db/changelog/computational-annotator-seeds` are missing. Or should they be created on the fly?

@Garrafao I think it would be best to package everything as a docker container, and at least document these things somewhere. Because the db runs in docker anyway, why not have phitag in a container as well?

**Comment by sachinn12** [comment]
@nilsreiter Hi, please comment the computational annotator seed line in db.changelog.development.xml file, then run again. It will work
![Uploading Screenshot_20240305-153031.png…]()

**Comment by Garrafao** [comment]
We a

> @Garrafao I think it would be best to package everything as a docker container, and at least document these things somewhere. Because the db runs in docker anyway, why not have phitag in a container as well?

That's what we are implementing right now. We'll post an update here this week.

**Comment by sachinn12** [comment]
@nilsreiter  Hi, could you please share your docker file script for the backend you wrote?I want to test in my system.

**Comment by nilsreiter** [comment]
Ok, so we now have a running system in our infrastructure. 

Phitag runs, alongside Inception, WebAnno and others, in a Docker container behind an nginx proxy. This makes everything a bit more complicated than expected.

Things I had to change:

- DB hostname (see above)
- The backend port and address, because `localhost:8080` doesn't work for the Browser (not sure why this works in your setup). In our setup, the backend is now under `/phitag-backend`, and nginx routes this to `phitag:8081` (inside the dockerized network)
- Frontend base path (see above)

The Docker file we wrote for phitag:

```
FROM debian:11
SHELL ["/bin/bash", "--login", "-c"]
EXPOSE 3000/tcp
EXPOSE 5432/tcp
EXPOSE 8081/tcp
EXPOSE 58080/tcp
RUN apt -y update
RUN apt -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common python3 pip
RUN apt -y install openjdk-17-jre-headless
RUN apt -y install maven
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt -y update
RUN apt -y install yarn
#RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN nvm install 14

WORKDIR /phitag
COPY src/pom.xml .

WORKDIR /phitag/backend
COPY src/backend/pom.xml .
COPY src/backend/src ./src
RUN mvn install

WORKDIR /phitag/frontend
COPY src/frontend/components components/
COPY src/frontend/lib lib/
COPY src/frontend/pages pages/
COPY public public/
COPY src/frontend/styles styles/
COPY src/frontend/.eslintrc.json .
COPY src/frontend/next-env.d.ts .
COPY src/frontend/next.config.js .
COPY src/frontend/package.json .
COPY src/frontend/postcss.config.js .
COPY src/frontend/tailwind.config.js .
COPY src/frontend/tsconfig.json .
RUN yarn install
 
CMD bash -c "cd /phitag/backend && mvn spring-boot:run -Dspring-boot.run.arguments='--server.port=8081' & sleep 25 && cd /phitag/frontend && yarn dev"
```

And the two service definitions from our docker-compose file:

```
  phitag-postgres:
    image: docker.io/postgres:11.5
    networks:
      spinfo-net:
    container_name: phitag-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: phitag
  phitag:
    build: phitag2
    hostname: phitag
    depends_on:
      - phitag-postgres
    networks:
      spinfo-net:

```

One final thing: I fought for some time with the regular expression to match the password -- the selection of special characters is limited and it would be nice to actually show them in the popup. :)

**Comment by sachinn12** [comment]
PhiTag can be run in a Docker container now. The guide to run Docker can be found in the [Readme](https://github.com/Garrafao/phitag/blob/main/README.md)."
