### ISSUE TITLE
instructions for tutorial phases -- error checking for gold judgments

### ISSUE THREAD

**Issue by cowsock** [Garrafao/phitag#92]
- Instructions for creating tutorial phases are either not present, or else not searchable in the tutorials list.

- It is not clear what additional column an instances file should need to indicate the correct answer (or hopefully correct answer**s** if that is possible!) for each task given in a tutorial phase. 

========

It looks like I need to upload a judgments file instead of having included the gold label in my instances file?

**Comment by sachinn12** [comment]
The instruction for creating tutorial will be uploaded soon.

**Comment by cowsock** [comment]
Update: I succeeded in uploading a judgments file to be able to take the tutorial that I authored - but I have not been able to pass my tutorial, to be allowed to access the phase that the tutorial was set as a requirement for.

It's possible that I did this in an order that was unexpected, as the tutorial phase was linked to the main phase as a requirement *before* it had any contents.

**Comment by sachinn12** [comment]
@cowsock  Hi, I checked your tutorial phase,  I saw you label (1 (unrelated)  and 4 ( identical) something like this  tutorial phase, please use only integer e.g. (1,2,3,4) in tutorial phase in both instance and judgement file . The agreement calculation metric is only designed to process integer value. You can use  your label in other phase.

**Comment by cowsock** [comment]
Could the labels just be mapped internally to integers? (I could create a new issue)
If the labels don't contain any instructions about their polarity, the user will need to have memorized the instructions, or have a page with them left open to consult. 

Ideally I would want something closer to a recreation of this interface from DURel: 

![Screenshot from 2024-03-04 16-47-28](https://github.com/Garrafao/phitag/assets/4561660/c56bd59e-d7ab-400e-b7b4-a578639c7bf1)

but I understand from the earlier discussion in #78 that you don't want to change the input format

**Comment by Garrafao** [comment]
> Could the labels just be mapped internally to integers? (I could create a new issue)

The problem with an internal mapping would be that it would have to be defined globally while the label set for each instance is currently defined locally (per instance). I wouldn't see a straightforward way to do this mapping without losing generality.

**Comment by Garrafao** [comment]
> Ideally I would want something closer to a recreation of this interface from DURel:

This should be possible, but some agreement calculation strategies may not be possible anymore. Your data will become nominal (not ordinal anymore). So, one possibility would be to compute the nominal version of Krippendorf. Another possibility would be to include the information of how judgments map to descriptions into the "Task Head" (specified when you create a new phase).

**Comment by cowsock** [comment]
> > Ideally I would want something closer to a recreation of this interface from DURel:
> 
> This should be possible, but some agreement calculation strategies may not be possible anymore. Your data will become nominal (not ordinal anymore). So, one possibility would be to compute the nominal version of Krippendorf. Another possibility would be to include the information of how judgments map to descriptions into the "Task Head" (specified when you create a new phase).

This would be a good solution -- the "Task Head" text just isn't displaying in the annotation interface.

**Comment by sachinn12** [comment]
The task head in the tutorial annotation has not been implemented yet,  you will see task head on tutorial from Monday
