### ISSUE TITLE
submit responses error message (where no error occurred)

### ISSUE THREAD

**Issue by cowsock** [Garrafao/phitag#94]
![phitag-error-message-submitting-responses](https://github.com/Garrafao/phitag/assets/4561660/70b460f9-1a3f-43dc-9633-e3fad07889f6)

Thanks for all of the updates in the last weeks!

I was just doing a test run of annotations for my study, and noticed this message appearing when attempting to submit my batch of responses. They were all successfully recorded -- but the message that pops up could be interpreted ominously by a study participant (like "contact the researcher?!?!? does this mean I'm not going to get paid for the work I just did?").

**Comment by sachinn12** [comment]
@cowsock Hi, I think you are using prolific features. In order to submit the study you need to paste the submission code in PhiTag. Please read this [guide.](https://phitag.ims.uni-stuttgart.de/guide/prolific-integration)

**Comment by cowsock** [comment]
Thank you, I had not yet tested having the submission code pasted into my Phase -- however, I am getting an error "Error uploading code" when I attempt to do so.

**Comment by cowsock** [comment]
@sachinn12 Could you check any logs about submitting a Prolific return code to a Phase? I'm not sure what I'm doing wrong or if it is currently broken.

**Comment by sachinn12** [comment]
@cowsock  Hi, could we schedule an online meeting after 11:00 PM tomorrow? Before that, I want to inform you that only prolific users can submit the study. If you are a PhiTag user, only then you can submit the study.

**Comment by cowsock** [comment]
Sorry, I was at a workshop today -- I can be available for a meeting on Monday if that works for you. My issue isn't with submitting a round of annotations (actually using the link back to Prolific) but in the actual pasting of the link back to Prolific -- attaching it to the Phase that I want to have people annotate.

**Comment by sachinn12** [comment]
@cowsock  Hi,  let's solve your issue today. Please let me know where and when we can meet.

**Comment by cowsock** [comment]
I'm at the IMS today -- down the hall from Dominick in the corner by the bathrooms on the 1 OG. Or if you prefer to talk on webex - my contact info is all here -> https://www.ims.uni-stuttgart.de/en/institute/team/Jenkins/
