### ISSUE TITLE
pop up menu for JobListing waiting list has no scrolling / is inaccessible past the first few entries

### ISSUE THREAD

**Issue by cowsock** [Garrafao/phitag#96]
Tested on Firefox and Chrome -- the collapsing menu for "Select Users¨  does not allow the full list to be viewed, if it is larger than the modal window "Add Users from Waitinglist"

**Comment by sachinn12** [comment]
The hidden issue for the user is now fixed. Commit:https://github.com/Garrafao/phitag/commit/b038e170b683ef8da10c948cf2884710d813745d
